<?php

/**
 * @file
 * General hook implementations.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function islandora_citations_form_field_config_edit_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $schema = json_decode(file_get_contents(__DIR__ . '/data/csl-data.json'), 1);

  if ($schema) {
    $cslPropertyArray = array_keys($schema['items']['properties']);
    $cslFieldOptions = array_combine($cslPropertyArray, $cslPropertyArray);
    $entity = $form_state->getFormObject()->getEntity();
    if ($entity->getType() == 'typed_relation') {
      $form['third_party_settings']['islandora_citations']['use_entity_checkbox'] = [
        '#title' => t('Map CSL from relation type'),
        '#description' => t('Enable mapping of this typed relation  field from the selected relation type. Rel types, author and creator both get mapped to author.'),
        '#type' => 'checkbox',
        '#required' => FALSE,
        '#default_value' => $entity->getThirdPartySetting('islandora_citations', 'use_entity_checkbox'),
      ];
    }
    else {
      $form['third_party_settings']['islandora_citations']['csl_field'] = [
        '#type' => 'select',
        '#title' => \t('CSL Field'),
        '#description' => \t('Select which CSL value this field should be mapped to.'),
        '#empty_option' => \t('- Select -'),
        '#multiple' => TRUE,
        '#options' => $cslFieldOptions,
        '#default_value' => $entity->getThirdPartySetting('islandora_citations', 'csl_field'),
      ];
      if ($entity->getType() == 'entity_reference') {
        $form['third_party_settings']['islandora_citations']['use_entity_checkbox'] = [
          '#title' => t('Map from entity'),
          '#description' => \t('If this field is enabled, the csl mapping will be taken from the referenced entity. Make sure you map fields in the referenced entity before enabling this.'),
          '#type' => 'checkbox',
          '#required' => FALSE,
          '#default_value' => $entity->getThirdPartySetting('islandora_citations', 'use_entity_checkbox'),
        ];
      }
    }
    return $form;
  }
}

/**
 * Implements hook_theme().
 */
function islandora_citations_theme($existing, $type, $theme, $path) {

  return [
    'display_citations' => [
      'render element' => 'form',
    ],
  ];
}
