<?php

/**
 * @file
 * General hook implementations.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function islandora_citations_form_field_config_edit_form_alter(&$form, FormStateInterface $form_state, $form_id) {

  $cslFieldConfig = \Drupal::config('islandora_citations.settings')->get('citation_fields');
  $cslFieldOptions = is_array($cslFieldConfig) ? array_combine($cslFieldConfig, $cslFieldConfig) : [];
  $entity = $form_state->getFormObject()->getEntity();
  $form['third_party_settings']['islandora_citations']['csl_field'] = [
    '#type' => 'select',
    '#title' => \t('CSL Field'),
    '#empty_option' => \t('- Select -'),
    '#multiple' => TRUE,
    '#options' => $cslFieldOptions,
    '#default_value' => $entity->getThirdPartySetting('islandora_citations', 'csl_field'),
  ];
  return $form;
}
