<?php

/**
 * @file
 * General hook implementations.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function islandora_citations_form_field_config_edit_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $schema = json_decode(file_get_contents(__DIR__ . '/data/csl-data.json'), 1);

  if ($schema) {
    $cslPropertyArray = array_keys($schema['items']['properties']);
    $cslFieldOptions = array_combine($cslPropertyArray, $cslPropertyArray);
    $entity = $form_state->getFormObject()->getEntity();
    $form['third_party_settings']['islandora_citations']['csl_field'] = [
      '#type' => 'select',
      '#title' => \t('CSL Field'),
      '#empty_option' => \t('- Select -'),
      '#multiple' => TRUE,
      '#options' => $cslFieldOptions,
      '#default_value' => $entity->getThirdPartySetting('islandora_citations', 'csl_field'),
    ];
    if ($entity->getType() == 'entity_reference') {
      $form['third_party_settings']['islandora_citations']['use_entity_checkbox'] = [
        '#title' => t('Map from entity'),
        '#type' => 'checkbox',
        '#required' => FALSE,
        '#default_value' => $entity->getThirdPartySetting('islandora_citations', 'use_entity_checkbox'),
      ];
    }
    return $form;
  }
}
