islandora_citations.islandora_citations.*:
  type: config_entity
  label: islandora_citations
  mapping:
    id:
      type: string
      label: ID
    label:
      type: label
      label: Label
    uuid:
      type: string
    csl:
      type: text

field.field.*.*.*.third_party.islandora_citations:
  type: mapping
  mapping:
    csl_field:
      type: sequence
      label: CSL Field
      sequence:
        type: string
        label: 'CSL'

islandora_citations.settings:
  type: config_object
  label: 'CSL field values'
  mapping:
    citation_fields:
      type: sequence
      label: 'CSL default field values'
      sequence:
        type: string
        label: 'CSL'
